CREATE DATABASE CASHIER;

USE CASHIER;

CREATE TABLE users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(50),
	password VARCHAR(50)
);

CREATE TABLE accounts (
	id INT AUTO_INCREMENT PRIMARY KEY,
	balance_pen DECIMAL(10, 2) DEFAULT 0.00,
	balance_usd DECIMAL(10, 2) DEFAULT 0.00,
	pwd VARCHAR(50)
);

INSERT INTO accounts VALUES (1, 10000, 20000, 'Hello world');
SELECT * FROM accounts;